---
- name: Start service container
  community.docker.docker_container:
    name: "{{ name }}"
    image: "{{ image }}"
    user: root
    command: "{{ command | default(omit) }}"
    env: "{{ config_env }}"
    published_ports: "{{ _port_list }}"
    network_mode: "{{ network_mode }}"
    volumes: "{{ _volume_list }}"
    cpus: "{{ cpus }}"
    memory: "{{ memory }}"
    restart_policy: "{{ restart_policy }}"
