---
- name: Load common service facts
  ansible.builtin.include_tasks: facts-common.yml

- name: Load systemd service facts
  ansible.builtin.include_tasks: facts-systemd.yml
  when: setup_mode == 'systemd'

- name: Load container service facts
  ansible.builtin.include_tasks: facts-container.yml
  when: setup_mode == 'container'
