---
name: Basic-Service Continuous-Integration
run-name: CI ${{ github.repository }} - ${{ github.ref }} job 🚀
on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Lint yaml and Ansible configs
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core==2.16.3 ansible-lint==24.12.2 yamllint==1.35.1
          yamllint --config-file ./tests/yaml-lint.yml .
          ansible-lint --config-file ./tests/ansible-lint.yml .
  molecule:
    strategy:
      matrix:
        scenario:
          - systemd-basic
          - systemd-full
          - systemd-uninstall
          - container-basic
          - container-full
          - container-uninstall
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule==25.9.0 molecule-docker==2.1.0 pytest-testinfra==10.2.2 ansible-core==2.16.3

      - name: Start Docker
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Run Molecule Test
        run: cd tests && molecule test -s ${{ matrix.scenario }}
